# ----------------------------
# Makefile Options
# ----------------------------

NAME = CEVIDIUM
ICON = iconc.png
DESCRIPTION = "CEVidium - Video Player"
COMPRESSED = NO
OUTPUT_MAP = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
